---
kind: pipeline
name: rust-stable

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: build
  image: rust:1.43
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build
- name: test
  image: rust:1.43
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse --short HEAD > .tags
- name: docker image
  image: plugins/docker
  settings:
    repo: mkroman/zeta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: rust-nightly

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: build
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build
- name: test
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
---
kind: signature
hmac: a84e3368c3d65a035c85108f4454e9dc5abfd1137eade4d8620bfab00e6811f5

...
