---
kind: pipeline
name: rust-stable

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: build
  image: rust:1.43
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build
- name: test
  image: rust:1.43
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse --short HEAD > .tags
    - pwd
- name: build release
  image: rust:1.43
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build --release
- name: docker image
  image: plugins/docker
  settings:
    repo: mkroman/zeta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: rust-nightly

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: build
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build
- name: test
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
---
kind: signature
hmac: 30d03fbc587f609570c698d11237c0f8df15245fb58ae3f77d3867288e07a3df

...
