---
kind: pipeline
name: rust-stable

steps:
- name: build
  image: rust:1.50
  commands:
    - cargo build

- name: test
  image: rust:1.50
  commands:
    - cargo test
    - git rev-parse HEAD > .tags

- name: build image
  image: plugins/docker
  when:
    branch:
      - master
      - deployment
  settings:
    repo: mkroman/zeta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: rust-nightly

steps:
- name: build
  image: rustlang/rust:nightly
  commands:
    - cargo build

- name: test
  image: rustlang/rust:nightly
  commands:
    - cargo test
---
kind: signature
hmac: 15e635eb8d6faa94f27dc279129ddd6858376f727ebe71a69232bb9ef8becae2

...
