---
kind: pipeline
name: rust-stable

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: build
  image: rust:1.43
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build
- name: test
  image: rust:1.43
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse --short HEAD > .tags
    - pwd
- name: docker image
  image: plugins/docker
  settings:
    repo: mkroman/zeta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: rust-nightly

volumes:
  - name: cargo-cache
    host:
      path: /var/lib/cargo-cache

steps:
- name: build
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build
- name: test
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
---
kind: signature
hmac: fe000e73f07e4a04233deed3f5f69274d5701ac479a94e1bdb3a39403bceaabb

...
