production: &base
  networks:
    - &uplink
      url: irc://znc.zeta:6667
      nickname: zeta
      channels:
        - '#uplink'

development:
  <<: *base

  networks:
    - &uplink
      url: ircs://irc.uplink.io:6667
      nickname: zeta-test
      channels:
        - '#test'
