# Database Configuration.
[database]
# PostgreSQL connection string.
url = "postgresql://user:changeme@localhost/zeta_development"

# The maximum idle duration for individual connections.
idle_timeout = "30s"

# The maximum number of connections that the database pool should maintain.
max_connections = 5

# IRC Configuration.
[irc]
# The client's nickname.
nickname = "zeta[dev]"

# Alternative nicknames for the client, if the default is taken.
alt_nicks = ["zet4", "z3ta", "z3t4", "zet_"]

# The client's username.
# username = "zeta"

# The client's real name.
# realname = "Zeta"

# The password to connect to the server.
# password = "password"

# The hostname of the server to connect to.
hostname = "irc.rwx.im"

# The port number of the server to connect to.
port = 6667

# Whether the client should use NickServ GHOST to reclaim its primary nickname if it is in use.
# This has no effect if `nick_password` is not set.
# should_ghost = true

# TLS Configuration.
[irc.tls]
# Toggle the use of TLS.
enabled = true

# List of channels to join. Can be specified multiple times.
[[irc.channels]]
# The name of the channel.
name = "#zeta.dev"
# The key to the channel if it's password protected.
# key = "test"

# [[irc.channels]]
# name = "#otherchannel"
# …

# DNS Configuration.
[dns]
# The number of retries after lookup failure before giving up.
# attempts = 2

# The size in number of records the cache can hold.
# cache_size = 32

# Plugin Configuration.
[plugins]
  [plugins.health]
  # Enable the plugin.
  enabled = true

  [plugins.dig]
  # Enable the plugin.
  enabled = true
  # List of nameservers to use for queries.
  nameservers = ["1.1.1.1", "1.0.0.1"]

# Tracing Configuration.
[tracing]
# Toggle tracing
enabled = true
