name: Send a notification message

inputs:
  channel:
    description: The IRC channel to send the notification to
    required: true
  message:
    description: The message to send
    required: true
  network:
    description: The IRC network to send the notification to
    required: true
  token:
    description: The webhook access token
    required: true
  webhook-url:
    description: The URL to the webhook endpoint
    required: true

runs:
  using: node24
  main: src/index.js
