name: Release

on:
  push:
    tags:
      - 0.*

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  container_image:
    name: Container Image
    needs:
      - test
    uses: ./.github/workflows/container-image.yaml
    with:
      images: ghcr.io/${{ github.repository }}
      push: true
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    needs:
      - test
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { runner: ubuntu-latest, platform: linux, arch: amd64 }
          - { runner: ubuntu-latest, platform: linux, arch: arm64 }
          - { runner: macos-latest, platform: darwin, arch: aarch64 }
    outputs:
      version: ${{ steps.artifact.outputs.version }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # master
        with:
          toolchain: stable
      - name: Determine crate version
        id: artifact
        run: |-
          VERSION="$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.name == "zeta") | .version')"
          echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
      - name: Install cargo-auditable
        run: cargo install cargo-auditable
        # Note that we're deliberately avoiding reusing the build cache.
      - name: Build
        run: cargo auditable build --release
      - name: Upload executable
        uses: actions/upload-artifact@v7
        with:
          name: zeta-${{ matrix.platform }}-${{ matrix.arch }}
          path: target/release/zeta${{ matrix.platform == 'windows' && '.exe' || '' }}
