name: Test

on:
  workflow_call:
    inputs:
      args:
        description: "Arguments to pass on to cargo test and cargo clippy"
        default: "--all-features"
        type: string
      cache-on-failure:
        description: "Cache rust build artifacts despite failures"
        default: true
        type: boolean
      fail-fast:
        description: "Fail fast when a rust test fails"
        default: false
        type: boolean
      runner:
        description: "The GitHub runner to use"
        default: "ubuntu-latest"
        type: string
      toolchain:
        description: "Rust toolchain to use. Defaults to `stable`."
        default: "stable"
        type: string

      # The following inputs are ordered after the ones above because their
      # default values depends on them already being declared.
      cache-key:
        description: "Shared cache key"
        default: "ci-${{ inputs.toolchain }}"
        type: string
      clippy-args:
        description: "Arguments to pass on to clippy (defaults to `args` if not set)"
        default: "${{ inputs.args }}"
        type: string
      test-args:
        description: "Arguments to pass on to cargo test (defaults to `args` if not set)"
        default: "${{ inputs.args }}"
        type: string

permissions:
  contents: read

jobs:
  # Run unit tests only, i.e. no integration tests.
  test:
    name: Unit Tests
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v7
      - name: Install Rust ${{ inputs.toolchain }}
        uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # master
        with:
          toolchain: ${{ inputs.toolchain }}
      - name: Enable type layout randomization
        run: echo "RUSTFLAGS=${RUSTFLAGS} -Zrandomize-layout" >> "${GITHUB_ENV}"
        if: inputs.toolchain == 'nightly'
      - name: Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          shared-key: ${{ inputs.cache-key }}
          cache-on-failure: ${{ inputs.cache-on-failure }}
          save-if: ${{ github.ref == 'refs/heads/main' }}
          cache-targets: true
      - name: Run tests
        run: cargo test ${{ inputs.test-args }} ${{ !inputs.fail-fast && '--no-fail-fast' || '' }}

  # Clippy runs as its own job because it doesn't play nice and reuse the
  # intermediate artifacts built by `cargo test` anyway.
  clippy:
    name: Clippy Lints
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v7
      - name: Install Rust ${{ inputs.toolchain }}
        uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: clippy
      - name: Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          shared-key: ${{ inputs.cache-key }}
          save-if: false # Don't cache clippy artifacts
      - name: Run Clippy check
        uses: clechasseur/rs-clippy-check@20f338ad6648dedb921c00b023bc30c971ab9ed7 # v6.0.7
        with:
          args: ${{ inputs.clippy-args }}
